In [145]:
import pandas as pd
import numpy as np

In [146]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['A', 'B', 'C'], index=['x', 'y', 'z'])

In [147]:
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [148]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [149]:
df.index.size

3

In [150]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [151]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [152]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [153]:
df['A'].unique()

array([1, 4, 7])

In [154]:
result = pd.read_csv("data/results.csv")
result

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [155]:
result

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [156]:
result.sample(10, random_state=1)

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
288565,2020.0,Summer,Boxing,"Flyweight, Men (Olympic)",Yoel Finol,136459,VEN,NaN,17.0,True,NaN
57866,1972.0,Summer,Artistic Gymnastics (Gymnastics),"Floor Exercise, Women (Olympic)",Cathy Rigby,29279,USA,NaN,9.0,True,NaN
62957,1952.0,Summer,Artistic Gymnastics (Gymnastics),"Horizontal Bar, Men (Olympic)",Frank Turner,30180,GBR,NaN,106.0,True,NaN
269319,2012.0,Summer,Water Polo (Aquatics),"Water Polo, Men (Olympic)",Viktor Nagy,126005,HUN,Hungary,5.0,False,NaN
62254,1908.0,Summer,Artistic Gymnastics (Gymnastics),"Team All-Around, Men (Olympic)",Alphonse Pinoy,30008,FRA,France,5.0,False,NaN
269358,2016.0,Summer,Athletics,"50 kilometres Race Walk, Men (Olympic)",Miguel Ángel López,126029,ESP,NaN,NaN,False,NaN
75029,1996.0,Summer,Handball,"Handball, Women (Olympic)",Laurie Fellner,32933,USA,United States,8.0,False,NaN
19642,1960.0,Summer,Equestrian Jumping (Equestrian),"Team, Open (Olympic)",Sean Daly,11800,IRL,Loch Garman / Ireland,NaN,False,NaN
165394,1920.0,Summer,Athletics,"110 metres Hurdles, Men (Olympic)",Walker Smith,79066,USA,NaN,5.0,False,NaN
59966,1984.0,Summer,Artistic Gymnastics (Gymnastics),"Floor Exercise, Men (Olympic)",Tong Fei,29569,CHN,NaN,8.0,False,NaN

In [157]:
result.iloc[:, 1:3]

          type              discipline
0       Summer                  Tennis
1       Summer                  Tennis
2       Summer                  Tennis
3       Summer                  Tennis
4       Summer                  Tennis
...        ...                     ...
308403  Winter                    Luge
308404  Winter  Alpine Skiing (Skiing)
308405  Winter  Alpine Skiing (Skiing)
308406  Winter  Alpine Skiing (Skiing)
308407  Winter                     NaN

[308408 rows x 2 columns]

In [158]:
result.loc[[0, 1, 5]] #index based

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
5,1996.0,Summer,Tennis,"Singles, Men (Olympic)",Arnaud Boetsch,2,FRA,NaN,17.0,True,NaN

In [159]:
result.loc[1:5, ["type", 'event', 'discipline']] #row column based

     type                     event discipline
1  Summer    Doubles, Men (Olympic)     Tennis
2  Summer    Singles, Men (Olympic)     Tennis
3  Summer  Doubles, Mixed (Olympic)     Tennis
4  Summer    Doubles, Men (Olympic)     Tennis
5  Summer    Singles, Men (Olympic)     Tennis

In [160]:
result.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [161]:
result.index = result['athlete_id']
result.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
athlete_id,,,,,,,,,,,
1,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
1,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
1,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
1,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [162]:
result.loc[3:7]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
athlete_id,,,,,,,,,,,
3,1924.0,Summer,Tennis,"Singles, Men (Olympic)",Jean Borotra,3,FRA,NaN,4.0,False,NaN
3,1924.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean Borotra,3,FRA,Marguerite Billout,15.0,True,NaN
3,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Borotra,3,FRA,René Lacoste,3.0,False,Bronze
4,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jacques Brugnon,4,FRA,NaN,9.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jacques Brugnon,4,FRA,Jean-François Blanchy,4.0,False,NaN
4,1924.0,Summer,Tennis,"Doubles, Men (Olympic)",Jacques Brugnon,4,FRA,Henri Cochet,2.0,False,Silver
5,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Albert Canet,5,FRA,NaN,17.0,True,NaN
5,1912.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Albert Canet,5,FRA,Marguerite Broquedis,3.0,False,Bronze
5,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Albert Canet,5,FRA,Édouard Mény de Marangue,3.0,False,Bronze
6,1992.0,Summer,Table Tennis,"Singles, Men (Olympic)",Nicolas Chatelain,6,FRA,NaN,33.0,True,NaN
6,1992.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Nicolas Chatelain,6,FRA,Patrick Chila,17.0,True,NaN
7,1992.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Nicolas Chatelain,17.0,True,NaN
7,1996.0,Summer,Table Tennis,"Singles, Men (Olympic)",Patrick Chila,7,FRA,NaN,9.0,True,NaN
7,1996.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Christophe Legoût,9.0,True,NaN
7,2000.0,Summer,Table Tennis,"Doubles, Men (Olympic)",Patrick Chila,7,FRA,Jean-Philippe Gatien,3.0,False,Bronze
7,2004.0,Summer,Table Tennis,"Singles, Men (Olympic)",Patrick Chila,7,FRA,NaN,17.0,True,NaN
7,2008.0,Summer,Table Tennis,"Singles, Men (Olympic)",Patrick Chila,7,FRA,NaN,49.0,True,NaN

In [163]:
result.reset_index(inplace=True, drop=True)

In [164]:
result.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

__Accessing data__

In [165]:
result['year']

0         1912.0
1         1912.0
2         1920.0
3         1920.0
4         1920.0
           ...
308403    2022.0
308404    2022.0
308405    2022.0
308406    2022.0
308407    2022.0
Name: year, Length: 308408, dtype: float64

In [166]:
result.year

0         1912.0
1         1912.0
2         1920.0
3         1920.0
4         1920.0
           ...
308403    2022.0
308404    2022.0
308405    2022.0
308406    2022.0
308407    2022.0
Name: year, Length: 308408, dtype: float64

In [167]:
result.sort_values(['year', 'type'], ascending=[0, 0])#False, also 0 1 means true-false asc for column

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
173195,2022.0,Winter,Speed Skating (Skating),"3,000 metres, Women (Olympic)",Claudia Pechstein,82053,GER,NaN,20.0,False,NaN
173196,2022.0,Winter,Speed Skating (Skating),"Mass Start, Women (Olympic)",Claudia Pechstein,82053,GER,NaN,9.0,False,NaN
213793,2022.0,Winter,Alpine Skiing (Skiing),"Super G, Women (Olympic)",Sarah Schleper,99452,MEX,NaN,35.0,False,NaN
213794,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Sarah Schleper,99452,MEX,NaN,37.0,False,NaN
215139,2022.0,Winter,Ski Jumping (Skiing),"Normal Hill, Individual, Men (Olympic)",Simon Ammann,99870,SUI,NaN,25.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
203177,NaN,NaN,Fencing,"Sabre, Individual, Men (Olympic)",Lóránt Mészáros,95189,HUN,NaN,5.0,False,NaN
203178,NaN,NaN,Fencing,"Sabre, Team, Men (Olympic)",Lóránt Mészáros,95189,HUN,Hungary,4.0,False,NaN
217586,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Georgios Pantos,100811,GRE,Athens,NaN,False,NaN
217587,NaN,NaN,Football (Football),"Football, Men (Intercalated)",Alexandros Kalafatis,100812,GRE,Athens,NaN,False,NaN
271490,NaN,NaN,Diving (Aquatics),"Platform, Men (Intercalated)",Wilhelm Lindgren,127259,SWE,NaN,13.0,False,NaN

In [168]:
# for index, row in result.iterrows():
#     print(index)
#     print(row)
#     print("\n\n")

In [169]:
result.tail()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [170]:
result.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 23.8 MB

In [171]:
result.loc[result['year'] > 2020]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
173195,2022.0,Winter,Speed Skating (Skating),"3,000 metres, Women (Olympic)",Claudia Pechstein,82053,GER,NaN,20.0,False,NaN
173196,2022.0,Winter,Speed Skating (Skating),"Mass Start, Women (Olympic)",Claudia Pechstein,82053,GER,NaN,9.0,False,NaN
213793,2022.0,Winter,Alpine Skiing (Skiing),"Super G, Women (Olympic)",Sarah Schleper,99452,MEX,NaN,35.0,False,NaN
213794,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Sarah Schleper,99452,MEX,NaN,37.0,False,NaN
215139,2022.0,Winter,Ski Jumping (Skiing),"Normal Hill, Individual, Men (Olympic)",Simon Ammann,99870,SUI,NaN,25.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [172]:
result[result['year'] > 2020]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
173195,2022.0,Winter,Speed Skating (Skating),"3,000 metres, Women (Olympic)",Claudia Pechstein,82053,GER,NaN,20.0,False,NaN
173196,2022.0,Winter,Speed Skating (Skating),"Mass Start, Women (Olympic)",Claudia Pechstein,82053,GER,NaN,9.0,False,NaN
213793,2022.0,Winter,Alpine Skiing (Skiing),"Super G, Women (Olympic)",Sarah Schleper,99452,MEX,NaN,35.0,False,NaN
213794,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Sarah Schleper,99452,MEX,NaN,37.0,False,NaN
215139,2022.0,Winter,Ski Jumping (Skiing),"Normal Hill, Individual, Men (Olympic)",Simon Ammann,99870,SUI,NaN,25.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [173]:
result[result['year'] > 2020][['year', 'type']]

          year    type
173195  2022.0  Winter
173196  2022.0  Winter
213793  2022.0  Winter
213794  2022.0  Winter
215139  2022.0  Winter
...        ...     ...
308403  2022.0  Winter
308404  2022.0  Winter
308405  2022.0  Winter
308406  2022.0  Winter
308407  2022.0  Winter

[4744 rows x 2 columns]

In [174]:
result[(result['year'] > 2020) & (result['noc'] == 'GER')][['year', 'type', 'noc']]

          year    type  noc
173195  2022.0  Winter  GER
173196  2022.0  Winter  GER
254675  2022.0  Winter  GER
254676  2022.0  Winter  GER
257150  2022.0  Winter  GER
...        ...     ...  ...
307465  2022.0  Winter  GER
307466  2022.0  Winter  GER
307467  2022.0  Winter  GER
307468  2022.0  Winter  GER
307469  2022.0  Winter  GER

[257 rows x 3 columns]

In [175]:
result[result['discipline'].str.contains("alpine|ski", case=False)]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
29420,1924.0,Winter,Cross Country Skiing (Skiing),"18 kilometres, Men (Olympic)",Roberts Plūme,16155,LAT,NaN,NaN,False,NaN
29421,1924.0,Winter,Cross Country Skiing (Skiing),"50 kilometres, Men (Olympic)",Roberts Plūme,16155,LAT,NaN,NaN,False,NaN
74584,1936.0,Winter,Alpine Skiing (Skiing),"Combined, Men (Olympic)",Willi Zacharias,32613,ROU,NaN,NaN,False,NaN
74585,1936.0,Winter,Alpine Skiing (Skiing),Cross Country Skiing (Skiing),Willi Zacharias,32613,ROU,ROU,NaN,True,NaN
74586,1936.0,Winter,Alpine Skiing (Skiing),"4 × 10 kilometres Relay, Men (Olympic)",Willi Zacharias,32613,ROU,Romania,14.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308385,2022.0,Winter,Cross Country Skiing (Skiing),"50 kilometres, Men (Olympic)",Ján Koristek,148965,SVK,NaN,40.0,False,NaN
308386,2022.0,Winter,Cross Country Skiing (Skiing),"30 kilometres Skiathlon, Men (Olympic)",Ján Koristek,148965,SVK,NaN,45.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN

In [176]:
result[(result['noc'].isin(['USA', "GER", 'FRA'])) & (result['event'].str.lower().str.startswith("singles"))]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
5,1996.0,Summer,Tennis,"Singles, Men (Olympic)",Arnaud Boetsch,2,FRA,NaN,17.0,True,NaN
7,1924.0,Summer,Tennis,"Singles, Men (Olympic)",Jean Borotra,3,FRA,NaN,4.0,False,NaN
10,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jacques Brugnon,4,FRA,NaN,9.0,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...
306105,2020.0,Summer,Table Tennis,"Singles, Men (Olympic)",Nikhil Kumar,147487,USA,NaN,33.0,True,NaN
307296,2022.0,Winter,Figure Skating (Skating),"Singles, Men (Olympic)",Kévin Aymoz,148338,FRA,NaN,12.0,False,NaN
307441,2022.0,Winter,Luge,"Singles, Women (Olympic)",Anna Berreiter,148429,GER,NaN,2.0,False,Silver
307442,2022.0,Winter,Luge,"Singles, Women (Olympic)",Julia Taubitz,148430,GER,NaN,7.0,False,NaN
307443,2022.0,Winter,Luge,"Singles, Men (Olympic)",Max Langenhan,148431,GER,NaN,6.0,False,NaN

__Modify dataframe__

In [177]:
coffee = pd.read_csv('data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [178]:
coffee['price'] = 4.99

In [179]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [180]:
coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99, 5.99)

In [181]:
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [182]:
coffee.drop(0, inplace=True)

In [183]:
coffee.drop(columns=['price'], inplace=True)

In [184]:
coffee.head()

         Day Coffee Type  Units Sold  new_price
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99
5  Wednesday       Latte          25       5.99

In [186]:
coffee_new = coffee.copy() #in case if we want to get same dataframe because in other way it will point to the same memory which means if we modify first dataframe second will be also affected

In [187]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [188]:
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65
5  Wednesday       Latte          25       5.99   149.75

In [190]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)

In [191]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65
5  Wednesday       Latte          25   5.99   149.75

In [192]:
result_new = pd.read_csv('data/results.csv')
result_new

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [193]:
print(result_new.head(1))

     year    type discipline                   event                     as  \
0  1912.0  Summer     Tennis  Singles, Men (Olympic)  Jean-François Blanchy

   athlete_id  noc team  place  tied medal
0           1  FRA  NaN   17.0  True   NaN

In [194]:
result_new['first_name'] = result_new['as'].str.split(" ").str[0]

In [195]:
result_new['first_name'].head()

0    Jean-François
1    Jean-François
2    Jean-François
3    Jean-François
4    Jean-François
Name: first_name, dtype: object

In [196]:
#we can convert object/string date into helpful type datetime using pd.to_datetime()

__Handling null values__

In [204]:
coffee.loc[[1, 2], 'Units Sold'] = np.nan

In [205]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

In [202]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
1     Monday       Latte         NaN   5.99    89.85
2    Tuesday    Espresso         NaN   3.99   119.70
3    Tuesday       Latte        20.0   5.99   119.80
4  Wednesday    Espresso        35.0   3.99   139.65
5  Wednesday       Latte        25.0   5.99   149.75

In [203]:
coffee = coffee.fillna(coffee['Units Sold'].median())
#todo: also can do dropna(subset=[column name], inplace=bool) but be careful

In [207]:
coffee[coffee['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price  revenue
1   Monday       Latte         NaN   5.99    89.85
2  Tuesday    Espresso         NaN   3.99   119.70

In [208]:
coffee[coffee.isna().any(axis=1)]

       Day Coffee Type  Units Sold  price  revenue
1   Monday       Latte         NaN   5.99    89.85
2  Tuesday    Espresso         NaN   3.99   119.70

In [209]:
result['noc'].value_counts()

noc
USA    21353
FRA    14276
GBR    13170
ITA    12129
CAN    11455
       ...
YAR       12
TUV        9
YMD        5
SSD        5
NBO        3
Name: count, Length: 230, dtype: int64

In [211]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    42.0
Latte       30.0
Name: Units Sold, dtype: float64